### ISSUE TITLE
When stopping/starting, the remaining sound in the queue plays before the new song start.

### ISSUE THREAD

**Issue by pgregory** [pgregory/wetracker#12]
Need to find a way to flush the sound buffers when stopping playback and starting a new, or replaying the current song from the start.

**Comment by a1k0n** [comment]
Yeah, the jsxm pause functionality just disconnects the ScriptProcessorNode from the output entirely, which leaves everything in its buffer... instead, you'll have to pause the pattern row processing but leave the audio engine running, and silence all the channels or something.

jsxm's sequence playback and audio engine are a bit tightly coupled, and you'll have to break that for an interactive editor if you want to use it...

**Comment by a1k0n** [comment]
I think you can close this, except now, you need to add a "stop" button which releases notes in all channels. :)

**Comment by pgregory** [comment]
This specific issue is no longer relevant, the player has changes significantly since reporting this. There are other issues that capture any remaining problems. Closing.
