### ISSUE TITLE
KeyboardJS seems to suck CPU

### ISSUE THREAD

**Issue by pgregory** [pgregory/wetracker#40]
## Description

When holding a key for the virtual keyboard, something goes awry in the system, Chrome gets stuck in a mode where it is drawing CPU constantly, even thought the key is released. There doesn't seem to be anything in the WeTracker code causing this, as the VKB is only triggering a note on the key down, and then forcing no repeat, so I'm presuming it's something in the KeyboardJS code that is getting caught up.

## Steps to reproduce

1. Load WeTracker with the default empty song, with two instruments.
2. Switch to instrument 2, the pad sound with looping.
3. Hold the 'z' key down for a while, causing the instrument to play in a loop.
4. Release the note.
5. Review CPU usage of Chrome in the system process monitor.

# Versions

- OS: macOS Sierra 10.12.2
- Browser: Chrome Mac 55.0.2883.95 (64-bit)

**Comment by a1k0n** [comment]
Yep. The javascript profiler confirms:

<img width="1185" alt="screen shot 2016-12-31 at 9 15 55 pm" src="https://cloud.githubusercontent.com/assets/46170/21580273/703b81a4-cf9e-11e6-9d93-fa14837d2c4d.png">

<img width="611" alt="screen shot 2016-12-31 at 9 16 16 pm" src="https://cloud.githubusercontent.com/assets/46170/21580274/72da0994-cf9e-11e6-85b8-3967da5b94eb.png">

pretty sure what's happening is that the keys are repeating, and it has to check to see if the repeated key is the same as what's already down.... that's a pretty heavy-handed way to do it. I wouldn't use that library...
