### ISSUE TITLE
No longer maintained?

### ISSUE THREAD

**Issue by Teteros** [pgregory/wetracker#83]
```bash
git clone --depth 1 https://github.com/pgregory/wetracker.git wetracker && cd $_
npm install
npm run start
```
> wetracker@1.0.0 start /tmp/wetracker
> node server.js
> server started 5000

Going on http://localhost:5000 gives a blank page with a bar:

![ss](https://user-images.githubusercontent.com/5067989/42263789-f19e60a8-7f66-11e8-8fda-f693ffad53c6.png)

`npm --version`
6.1.0
`node --version`
v10.5.0

**Comment by pgregory** [comment]
Looks like an issue with jquery.fancytree. Investigating now. This project has gone a little quite of late, but I plan to return to it properly soon, so it has stagnated a little in terms of it's dependencies.
